# ==========================================
# QRSmartOEE Docker Compose Configuration
# ==========================================

services:
  # ======================
  # PostgreSQL Database
  # ======================
  postgres:
    image: postgres:16
    container_name: qrsmart-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "P@ssw0rd"
      POSTGRES_DB: qrsmartoee
    ports:
      - "5434:5432"
    volumes:
      - ./app-data/db:/var/lib/postgresql/data
    networks:
      - qrsmart-net

  # ======================
  # NestJS API Service (QR)
  # ======================
  api:
    build: ./api
    container_name: qrsmart-api
    restart: always
    environment:
      SITE_ID: 1
      PORT: 8000
      HTTP_BASIC_USER: admin
      HTTP_BASIC_PASS: "P@ssw0rd1"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: "P@ssw0rd"
      DB_DATABASE: qrsmartoee
      TCP_SERVER_HOST: 172.18.40.12
      TCP_SERVER_PORT: 4196
      MODBUS_IP: 172.18.40.11
      MODBUS_PORT: 506
    depends_on:
      - postgres
    networks:
      - qrsmart-net

  # ======================
  # Next.js Client Service
  # ======================
  client:
    build: ./client
    container_name: qrsmart-client
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_QR_API_USERNAME: admin
      NEXT_PUBLIC_QR_API_PASSWORD: "P@ssw0rd1"
      NEXT_PUBLIC_OEE_API_URL: http://host.docker.internal:3010
      NEXT_PUBLIC_QR_API_URL: http://qrsmart-api:8000
    depends_on:
      - api
    networks:
      - qrsmart-net

  # ======================
  # Nginx Reverse Proxy
  # ======================
  proxy:
    image: nginx:1.27-alpine
    container_name: qrsmart-proxy
    restart: always
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - api
    networks:
      - qrsmart-net
      - oee-net

# ======================
# Network Definitions
# ======================
networks:
  qrsmart-net:
    driver: bridge

  oee-net:
    external: true
    name: smartoee_default
