services:
  # ======================
  # PostgreSQL Database
  # ======================
  postgres:
    image: postgres:16
    container_name: qrsmart-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: qrsmartoee
    ports:
      - "5434:5432"
    volumes:
      - ./app-data/db:/var/lib/postgresql/data
    networks:
      - qrsmart-net

  # ======================
  # NestJS API Service
  # ======================
  api:
    build: ./api
    container_name: qrsmart-api
    restart: always
    environment:
      SITE_ID: 1
      PORT: 8000
      HTTP_BASIC_USER: admin
      HTTP_BASIC_PASS: password123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: P@ssw0rd
      DB_DATABASE: qrsmartoee
      TCP_SERVER_HOST: 172.18.40.12
      TCP_SERVER_PORT: 4196
      MODBUS_IP: 172.18.40.11
      MODBUS_PORT: 506
    depends_on:
      - postgres
    networks:
      - qrsmart-net

  # ======================
  # Next.js Client Service
  # ======================
  client:
    build: ./client
    container_name: qrsmart-client
    restart: always
    environment:
      NEXT_PUBLIC_QR_API_USERNAME: admin
      NEXT_PUBLIC_QR_API_PASSWORD: password123
    depends_on:
      - api
    networks:
      - qrsmart-net

  # ======================
  # Nginx Reverse Proxy (ตัวใหม่ที่เพิ่มเข้ามา)
  # ======================
  proxy:
    image: nginx:1.27-alpine # ใช้อิมเมจ Nginx
    container_name: qrsmart-proxy
    restart: always
    ports:
      - "4000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - qrsmart-net
    depends_on:
      - client
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  qrsmart-net:
    driver: bridge

